set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set-option -g status-position top
# Toggle status line with prefix + t
bind t set-option -g status

set-option -sg escape-time 10
set-option -g focus-events on


set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind %
bind | split-window -h -c '#{pane_current_path}'  # Split panes horizontal

unbind '"'
bind - split-window -v -c '#{pane_current_path}'  # Split panes vertically

bind c new-window -c '#{pane_current_path}' # Create new window

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z
set -gq allow-passthrough on
set -g visual-activity off
set -g mouse on
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#latest'
set -g @catppuccin_flavor 'mocha'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'ok'
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'
