#!/usr/bin/env bash
## Description: Open lazysql on a project database
## Usage: lazysql [database] [-p project]
## Example: "ddev lazysql\nddev lazysql -p auth\nddev lazysql mydb -p auth"
## Flags: [{"Name":"project","Shorthand":"p","Usage":"project name (default: current dir)","Type":"string"}]
## HostBinaryExists: /opt/homebrew/bin/lazysql
## CanRunGlobally: true

PROJECT="${DDEV_PROJECT}"
DATABASE=""
while [ $# -gt 0 ]; do
  case "$1" in
    -p|--project) PROJECT="$2"; shift ;;
    --project=*)  PROJECT="${1#*=}" ;;
    *)            DATABASE="$1" ;;
  esac
  shift
done
[ -z "$PROJECT" ] && { echo "Not in a project; use -p <project>"; exit 1; }

if [ "$(ddev describe -j "$PROJECT" | jq -r .raw.status)" != "running" ]; then
  echo "Project ${PROJECT} is not running, starting it"
  ddev start "$PROJECT" || exit $?
fi

eval "$(ddev describe -j "$PROJECT" | jq -r '.raw.dbinfo | "PORT=\(.published_port) FAMILY=\(.database_type) DBNAME=\(.dbname) USER=\(.username) PASS=\(.password)"')"
DATABASE="${DATABASE:-$DBNAME}"

case "$FAMILY" in
  postgres) URL="postgres://${USER}:${PASS}@127.0.0.1:${PORT}/${DATABASE}?sslmode=disable" ;;
  *)        URL="mysql://${USER}:${PASS}@127.0.0.1:${PORT}/${DATABASE}" ;;
esac

exec lazysql "$URL"
