local kulala = require("kulala")
local keymap = vim.keymap

keymap.set("n", "<leader>rr", function()
	kulala.run()
end, { desc = "Run Current HTTP Request", noremap = true, silent = true })
keymap.set("n", "<leader>ra", function()
	kulala.run_all()
end, { desc = "Run All Requests in Buffer", noremap = true, silent = true })
keymap.set("n", "<leader>rp", function()
	kulala.replay()
end, { desc = "Replay Last Request", noremap = true, silent = true })
keymap.set("n", "<leader>ri", function()
	kulala.inspect()
end, { desc = "Inspect Request", noremap = true, silent = true })
keymap.set("n", "<leader>rc", function()
	kulala.copy()
end, { desc = "Copy Request as cURL", noremap = true, silent = true })
keymap.set("n", "<leader>rf", function()
	kulala.from_curl()
end, { desc = "Import cURL from Clipboard", noremap = true, silent = true })
keymap.set("n", "<leader>rt", function()
	kulala.toggle_view()
end, { desc = "Toggle Response View", noremap = true, silent = true })
keymap.set("n", "<leader>rx", function()
	kulala.close()
end, { desc = "Close current kulala", noremap = true, silent = true })
keymap.set("n", "<leader>rn", function()
	kulala.search()
end, { desc = "Search Named Requests", noremap = true, silent = true })
keymap.set("n", "<leader>rk", function()
	kulala.jump_prev()
	vim.cmd("normal! zz")
end, { desc = "Jump to Previous Request", noremap = true, silent = true })
keymap.set("n", "<leader>rj", function()
	kulala.jump_next()
	vim.cmd("normal! zz")
end, { desc = "Jump to Next Request", noremap = true, silent = true })
keymap.set("n", "<leader>re", function()
	kulala.get_selected_env()
end, { desc = "Get Selected Environment", noremap = true, silent = true })
keymap.set("n", "<leader>rE", function()
	kulala.set_selected_env()
end, { desc = "Set Environment", noremap = true, silent = true })
keymap.set("n", "<leader>rs", function()
	kulala.download_graphql_schema()
end, { desc = "Download Graphql Schema", noremap = true, silent = true })
