[kongvanny2000@gmail.com]
source        = imaps://kongvanny2000%40gmail.com@imap.gmail.com:993
outgoing      = smtp://kongvanny2000%40gmail.com@smtp.gmail.com:587
source-cred-cmd = pass show personal/gmail/kongvanny2000@gmail.com/app_passwords/aerc
outgoing-cred-cmd = pass show personal/gmail/kongvanny2000@gmail.com/app_passwords/aerc
default       = INBOX
from          = Kong Vanny <kongvanny2000@gmail.com>
cache-headers = true

[shoprunback]
source            = imaps+xoauth2://vanny%40shoprunback.com@outlook.office365.com:993
outgoing          = smtp+xoauth2://vanny%40shoprunback.com@smtp.office365.com:587
from              = Vanny <vanny@shoprunback.com>
default           = INBOX
copy-to           = Sent Items
folders           = INBOX,Sent Items,Drafts,Deleted Items,Junk Email, Archive
cache-headers     = true
source-cred-cmd   = oama access vanny@shoprunback.com
outgoing-cred-cmd = oama access vanny@shoprunback.com
