[kongvanny2000@gmail.com]
source        = imaps://kongvanny2000%40gmail.com@imap.gmail.com:993
outgoing      = smtp://kongvanny2000%40gmail.com@smtp.gmail.com:587
source-cred-cmd = pass show personal/gmail/kongvanny2000@gmail.com/app_passwords/aerc
outgoing-cred-cmd = pass show personal/gmail/kongvanny2000@gmail.com/app_passwords/aerc
default       = INBOX
from          = Kong Vanny <kongvanny2000@gmail.com>
cache-headers = true

